# Generated by Django 4.1.6 on 2023-10-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200, null=True)),
                ('Last_Name', models.CharField(max_length=200, null=True)),
                ('Mobile', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=200)),
                ('Booking_Date', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
            ],
        ),
    ]
