# Generated by Django 4.1.6 on 2023-10-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_booking_options_alter_booking_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
    ]
