# Generated by Django 4.1.6 on 2023-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_booking_options_alter_booking_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
    ]
