# Generated by Django 4.1.6 on 2023-10-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
