# Generated by Django 4.1.6 on 2023-10-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_rename_booking_date_booking_for_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='for_date',
            new_name='Booking_Date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_booking',
        ),
    ]
