# Generated by Django 4.1.6 on 2023-10-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_rename_for_date_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_h1', models.CharField(max_length=200)),
                ('text_p', models.CharField(max_length=200)),
            ],
        ),
    ]
