# Generated by Django 4.2.6 on 2023-11-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_image_delete_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallary_Post',
        ),
    ]
