# Generated by Django 4.2.6 on 2023-11-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_gallary_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallary_Post',
            new_name='Gallery_Post',
        ),
    ]
