# Generated by Django 4.2.6 on 2023-11-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_rename_gallary_post_gallery_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery_Post',
            new_name='Gallary_Post',
        ),
    ]
