# Generated by Django 4.2.6 on 2023-11-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200, null=True)),
                ('Last_Name', models.CharField(max_length=200, null=True)),
                ('Mobile', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=200)),
                ('Booking_for', models.CharField(max_length=100)),
                ('Time_for', models.CharField(max_length=100)),
                ('Booking_Date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
